#!/bin/sh

set -e

if [ -z "$1" ] || [ -z "$2" ] ; then
	echo "Wrong arguments" > /dev/stderr
	exit 1
fi

aroio_control_led blink 0.15 0.15 5 2 0

# Check out the state of our NICs
function checkinterfaces()
{
	until [[ "$ETH0_SETUP" = "configured" || "$WLAN0_SETUP" = "configured" ]]
	do
		ETH0_STATE=$(networkctl status eth0 | awk '/State/ {print $2}')
		WLAN0_STATE=$(networkctl status wlan0 | awk '/State/ {print $2}')
		ETH0_SETUP=$(networkctl | awk '/eth0/ {print $5}')
		WLAN0_SETUP=$(networkctl | awk '/wlan0/ {print $5}')
		echo "eth0 state:  "$ETH0_STATE
		echo "eth0 setup:  "$ETH0_SETUP
		echo "wlan0 state: "$WLAN0_STATE
		echo "wlan0 setup: "$WLAN0_SETUP
		sleep 0.5
	done
}

checkinterfaces

if [[ "$ETH0_STATE" = "routable"  &&  "$ETH0_SETUP" = "configured" || "$WLAN0_STATE" = "routable"  &&  "$WLAN0_SETUP" = "configured" ]]
then
	echo "We have a configured network!"
	echo "Will turn LED on!"
	aroio_control_led on
else
	echo "The interface(s) didn't manage to get configured properly!"
fi
exit 0
